name: task_list_app
description: Task list application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+8

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  beamer: ^1.5.3
  dio: ^4.0.6
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  hooks_riverpod: ^2.1.3
  flutter:
    sdk: flutter
  # Facilitates i8n and l10n
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^2.0.0
  intl: ^0.17.0
  url_launcher: ^6.1.7
  riverpod_context: ^0.3.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0    # Facilitates linting

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
